#!/bin/bash
if [ $1 = "--install" ]; then
    sudo apt update
    sudo apt install software-properties-common
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt update
    sudo apt install python3.8
elif [ $1 = "--test" ]; then
    # test a number of different binaries at once
elif [ $# = 2 ]; then
    # run the fuzzer
else; then
    echo "./fuzzer [options]"
    echo "       - install"
    echo "       - [--test] binary_name input_name"
fi